site_name: Guide de gestion de données

site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: assets/ogsl-logo-white.png
  palette:  
    primary: "white"
    accent: "light-blue"

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    # - navigation.footer

nav:
  - Accueil: index.md
  - Guide: draft.md
  - A propos: a-propos.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OGSL-SLGO

markdown_extensions:
  - attr_list