site_name: Guide de gestion de données
site_url: https://cioos-siooc.github.io/cioos-siooc-guide/
repo_url: https://github.com/cioos-siooc/cioos-siooc-guide/
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/logos/favicon.svg
  favicon: assets/logos/favicon.png
  palette:  
    primary: teal
    accent: blue
  font:
    text: Montserrat


  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    # - navigation.footer
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit

extra_css:
  - assets/styles/header.css

nav:
  - Home: index.md
  - Guide:
    - ./guide/accueil.md
    - ./guide/faircare.md
    - ./guide/recommendations.md
    - ./guide/dictionnaire.md
    - ./guide/template.md
    - ./guide/ressources.md
    - ./guide/annexes.md
  - Data Management Plan: 
    - ./PGD/Définitions.md
    - ./PGD/PGDCIOOS.md

extra:
  alternate:  
      # Switch to English
    - name: English
      link: /en/
      lang: en
    # Switch to French
    - name: Français
      link: /fr/
      lang: fr

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cioos-siooc

plugins:
  - search:                                         
      lang: fr  
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          name: English
          site_name: Canadian Integrated Ocean Observing System<br>Data Management Guide
          build: true
        - locale: fr
          name: Français
          site_name: Système intégré d'observation des océans du Canada<br>Guide de gestion de données
          default: true
          build: true
          nav_translations:
            Home: Accueil
            Guide: Guide
            Data Management Plan: Plan de gestion de données
  # - git-revision-date-localized:
  #     enable_creation_date: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
