site_name: Guide de gestion de données
docs_dir: ./../../docs/fr 
site_dir: ./../../site/fr
site_url: https://mydomain.org/mysite

theme:
  name: material
  logo: images/cioos-national_EN_W-01.png
  favicon: images/favicon.png
  custom_dir: ./../../overrides
  language: fr
  palette:  
    primary: teal
    accent: blue
  font:
    text: Roboto


  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    # - navigation.footer

extra_css:
  - assets/styles/header.css

nav:
  - Accueil: index.md
  - Guide:
    - Introduction: guide.md
    - Principes FAIR: ./guide/fair.md
  - A propos: about.md

extra:
  alternate:  
      # Switch to English
    - name: English
      link: /en/
      lang: en
    # Switch to French
    - name: Français
      link: /fr/
      lang: fr

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cioos-siooc

plugins:
  - search:                                         
      lang: fr  

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
