name: Build and Deploy Website

on:
  push:
    branches:
      - main
      - development
  pull_requests:
    branches:
      - development

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Deploy docs with mike
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [ "$BRANCH_NAME" = "main" ]; then
            uv run mike deploy --push "$BRANCH_NAME" latest
            uv run mike set-default --push latest
          else
            uv run mike deploy --push "$BRANCH_NAME"
          fi
